services:
  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=__init__.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - SCHEMA=food_bridge_schema
      - SECRET_KEY=dev
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: